all: deepthroat thewashingtonpost

deepthroat: deepthroat.c
	gcc deepthroat.c -o deepthroat -Wall
	
thewashingtonpost: thewashingtonpost.c
	gcc thewashingtonpost.c -o thewashingtonpost -Wall -lm
	
clean:
	rm deepthroat
	rm thewashingtonpost
